sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: hSqTToLZwxN6AYBgp7dg20tqgq7MtyUND3me7aF1SdIl9LeBxzJvqKma8Bk1c5rvviuMQIlyrGDuosTAGftDEsOnwCoS6PUGv3XYgO3Rm7hxt6q/raPzWszjowNkF3YUkQpyCRPrRyVPvi1zg8LjPNF0JloNTpZWTsRfUEXw2UTDpA+IrnfCy4k6I9nZic+B7+4qwk3UK0hiNz410B1iO/nuBHaJHZBztOW2/U3cLMw2mNqwnkIdcbno0cdjl5M31GFLI1XmLaKX1tAd9qrID5PnVIS7gBreWL0gTRnh5Ar6YYQcW5b3gvZS8AjikOvVuKqPHRWnZKDr9yJxgY2tiHdneVSgTMdF8iUM1/BiGwuiV9t5aGiADdWgZdWok/vAfwnCD3dQ+BP/nnjObkjgesE6rDvKXy8c3UZYfxvBVcyvVdOhInPkPYxtAIe97j7DxBJoSeIz34JNsgh7tEFLLocTAjFWVWxsASl71wxBnOppyAqQuhSV5KYeQsLsPPxPkhXnjfA+RYJOjv6zsZhb9joAQapn4tVkKrX6F16537SVRfuXzrbfnAZN+oO0X/09FvfAzRW5TV52v4sX9TdU9KJP6wSTOZNRxAR0Hv3N0OZzs79OhFB0nWY02YO8Awbpfz9iYDH1r1DFObeFq3f8TgyPBXfTEK+iDbutmBSf1Nk=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Gentle-Grafter_1805
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy